#!/bin/sh
# Strip AI tool attribution from staged files.
# Runs as part of pre-commit to auto-clean, and pre-push to verify.
#
# Why: AI coding assistants inject co-authorship trailers, watermark comments,
# and tool-specific markers. These are noise that clutters git history and
# misrepresents authorship.
#
# Maintained list of known patterns. Add new ones as tools emerge.
# See docs/AI_ATTRIBUTION_POLICY.md for full documentation.

set -e

STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACM -- '*.ts' '*.tsx' '*.js' '*.jsx' '*.md' 2>/dev/null || true)

if [ -z "$STAGED_FILES" ]; then
  exit 0
fi

CHANGED=0

# --- Code comment watermarks ---
# These appear as comments in source code or text in markdown.
COMMENT_PATTERNS='
Created with Cursor
Generated by Copilot
Generated by Claude
Generated by ChatGPT
Generated by Codeium
Generated by Windsurf
Generated by Devin
Generated by Aider
Generated by Tabnine
Generated by Cody
Generated by Continue
Generated by Augment
Generated by Supermaven
cursor-ai
'

for pattern in $COMMENT_PATTERNS; do
  # Skip empty lines
  [ -z "$pattern" ] && continue
  for file in $STAGED_FILES; do
    if grep -q "$pattern" "$file" 2>/dev/null; then
      # Use portable sed (macOS + Linux)
      if [ "$(uname)" = "Darwin" ]; then
        sed -i '' "/$pattern/d" "$file"
      else
        sed -i "/$pattern/d" "$file"
      fi
      git add "$file"
      CHANGED=$((CHANGED + 1))
      echo "  stripped: '$pattern' from $file"
    fi
  done
done

if [ "$CHANGED" -gt 0 ]; then
  echo "AI attribution: stripped $CHANGED pattern(s) from staged files"
fi
